### PR TITLE
Fix duplicated upper and lower case properties file. Normalise all properties file to be lowercase

### PR DESCRIPTION
**Pull request by vicchi**
There are some property files which exist in uppercase and lowercase versions. The only difference between the files is the `id` property and the the case of the `name` property. This makes working on a case insensitive file system (the default under macOS) ... "fun".

Steps to replicate (on macOS 10.13.3 - Macintosh HD formatted as APFS, case insensitive)

```
$ git clone git@github.com:whosonfirst/whosonfirst-properties.git
Cloning into 'whosonfirst-properties'...
remote: Counting objects: 2388, done.
remote: Total 2388 (delta 0), reused 0 (delta 0), pack-reused 2388
Receiving objects: 100% (2388/2388), 285.94 KiB | 722.00 KiB/s, done.
Resolving deltas: 100% (733/733), done.
$ cd whosonfirst-properties/
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   properties/amsgis/CODE.json
	modified:   properties/amsgis/NAAM.json
	modified:   properties/cbsnl/GM_CODE.json
	modified:   properties/figov/Aluejako.json
	modified:   properties/fsgov/Aluejako.json
	modified:   properties/hkigis/KOKOTUNNUS.json
	modified:   properties/hkigis/NIMI.json
	modified:   properties/hkigis/TUNNUS.json

no changes added to commit (use "git add" and/or "git commit -a”)
```

And sure enough ...

```
$ git ls-tree HEAD properties/amsgis/ | grep -i naam
100644 blob b4f1c220a71d3725208601841579050b27a0ba45	properties/amsgis/NAAM.json
100644 blob 890c9bbaf4e2aaf01a71609cd920c51930c27050	properties/amsgis/naam.json

```

This PR resolves this problem and then goes further. In conversation with @thisisaaronland, he said ...

> 1. Things _should_ be lower-cased, across the board
> 2. Generally the rule has been _not_ to muck with source data, including names
> 3. That said this is why there is both a name (unique and lower-case) and a label (whatever case and not necessarily unique) property
> 4. My guess is that Stephen (Epps) maybe got 2 and 3 mixed up
> 5. When I did the bulk inventory I just went with whatever was in the documents, and didn’t massage the value
> 
> 5 is actually an important part because while it is frustrating it is also easy to fix and playing fast and loose -ish at the time allowed us to keep things moving. That rule doesn’t apply to everything but in this case it does. Also the “easy to fix (when it actually becomes an issue)” part.
> 
> In as much as there are bunk records that are easy to spot I would compile a list, put it in an issue and flag @stepps00  - feel free to copy 1-5 above 
> 
> 

Working on a removable volume, formatted as APFS, case _sensitive_ ... all property JSON files are now normalised to lowercase, from their uppercase and camel case originals, ensuring that the only change made is the case of the filename and the case of the `name` property.

### CODE REVIEW

**Comment by straup** [comment]
cc @stepps00 @nvkelso @dphiffer 

The only problem I have with this PR is that it is "lossy" - that is we lose the source name/label which may be upper or mixed-case. That makes any future comparisons or updates difficult.

Also despite what I said there doesn't appear to have ever been a `label` property... so we should add one. Or `src:name` but let's start with `label` and work from there.  That would mean:

* The `name` property is always lower-cased and normalized (so `_` in place of `-` and ASCII/URL-safe)
* Duplicate normalized `prefix:name` results means a human has to resolve the difference and give one of them a modified `name` value - the corollary to this might be a flag to tell the robots that "this one is special"
* Filenames map to `name`
* WOF records proper use `prefix:name` (rather than `prefix:label`)
* The `label` field is whatever the actual source (as defined by `prefix` which should map to something in `whosonfirst-sources`) says - for example, lots of the NE/QS properties are upper-cased because... well, because it's their party and not for us to say. In theory there should never be duplicate `prefix:label` pairs but that shouldn't be our concern, either way.

I would also prefer _not_ to delete or remove files, mostly on principal and as a best practice. It is one of the few "golden rules" for the actual WOF data so it seems best to apply the rule across the board.

Things that are bunk should have one or more of the following properties:

*  `edtf:deprecated: ISO-8061` 
* `mz:is_current:0` (`mz` is a bit of an odd-ball now so we will jokingly refer to it as "metazen" until it sticks...)
* `wof:superseded_by: [ {NAME} ]`

I mean that's what we do for data. I am not sure we _need_ to do the same for properties (it seems a bit pedantic, really...) but the issues are the same so we might as well. By extension that means adding `mz:is_current:1` and `wof:supersedes: []` to everything else but let's make that tomorrow's problem, today...

**Comment by vicchi** [comment]
@thisisaaronland So there's really two issues going on here which I've conflated.

The first is that there are 8 properties files which exist in all upper and all lowercase versions.

Either this is as intended, which means we need to mandate case sensitive file systems. Which probably isn't what's wanted.

Or this is a bug, which originated on a case sensitive file system and one of these files needs to be preserved and one of these needs to be removed, which by definition is _going_ to be lossy.

The second is the policy on file naming conventions and the properties these describe.

Why don't I re-issue this PR to fix just the first issue and move the discussion over the second issue to another (GitHub) issue?

**Comment by stepps00** [comment]
Adding my two cents here..

In regards to:

```
$ git ls-tree HEAD properties/amsgis/ | grep -i naam
100644 blob b4f1c220a71d3725208601841579050b27a0ba45	properties/amsgis/NAAM.json
100644 blob 890c9bbaf4e2aaf01a71609cd920c51930c27050	properties/amsgis/naam.json
```

both `amsgis:NAAM` and  `amsgis:naam` are existing properties in current WOF records. See the records for [Amerikahaven](https://spelunker.whosonfirst.org/id/1108803829/) (lowercase) and [Waterland](https://spelunker.whosonfirst.org/id/1108945271/) (uppercase) as examples. 

This leads into the five point list:

```
1. Things should be lower-cased, across the board
2. Generally the rule has been not to muck with source data, including names
3. That said this is why there is both a name (unique and lower-case) and a label (whatever case and not necessarily unique) property
4. My guess is that Stephen (Epps) maybe got 2 and 3 mixed up
5. When I did the bulk inventory I just went with whatever was in the documents, and didn’t massage the value
```

We've made an effort _not_ to muck with source data and to import source properties as they exist in source data. In the case of the `amsgis` data, both upper and lower case properties exist, depending on the placetype of the data provided. The json files in this case reflect properties as they currently exist in our records.

With the `naam`/`NAAM` example, if we decide to combine the two property files, we should at least retain some information or a flag to indicate that there are alternate versions/variations to the casing of the property. Ideally these json files can be used on case insensitive machines, so I'm open to ideas and willing to help fix files going forward.

**Comment by vicchi** [comment]
Not mucking with source data is generally a good idea. But from doing some digging this evening (as a beneficial side effect of seeing whether the current contents of the `whosonfirst-data` repo can be validated with the changes I've made to the `whosonfirst-json-schema` repos, which in turn was kicked off from trying to get WOF indexed in the latest version of ES, but I digress), there's quite a few case of upper and lower case properties in the WOF documents.

The Natural Earth Data properties in particular exhibit this, with `ne:GN_ASCII` and `ne:gn_ascii` existing both as property definitions (in this repo) and as properties in the WOF documents - though so far, not both forms in the same document, but that's not 100% certain.

The way I'm currently thinking about this is that this repo contains the canonical source of truth for all properties in a WOF document. We can then, later but soon, use these property definitions to build the JSON schema files for validating the WOF documents, which also means that the documents will be consistent.

I'll need to do some more digging but I suspect we can check for properties in a case insensitive manner and normalise across the board, to an all lower case property name manner. Just so long as none of the sources have _different_ data in their upper and lower cased variants. I really hope not, but we'd need to check.

Alternately we leave this _as is_ and put to onus on people using the data to normalise as part of their workflow. Which feels like cheating.

But where there's two properties files, identical apart from their (Brooklyn Integer) `id` property, this feels broken to me. We can't mandate case sensitive file systems (which cuts out 99.9% of Mac users), can we? It doesn't feel right to do so.

So how about the following ...

1. Property definition files are lowercase
2. Property names in the definition files are lowercase.
3. Where there's an uppercase originating form in the upstream source, this is added as a new, `source_name` property.
4. The absense of a `source_name` property in a definition file denotes that the property was always lowercase.

This way whilst there's a _lossy_ fix in removing the uppercase versions of the property definition files, there's no loss of history or context.

**Comment by vicchi** [comment]
One other thing to throw into the discussion ...

I'm currently writing a script (which should be fed from the property definition files, but isn't yet, until we sort those out) to try and normalise, in a non-lossy way, some of the differing property value representation in the WOF documents.

Examples include ...

Arrays of (numeric) identifiers being `int` in some cases and `str` in others so `"foo": [ "123", "456" ]` vs. `"foo": [ 123, 456 ]`. `wof:belongsto`, `wof:children` and `wof:supersedes` show this a lot.

Ditto for scalar properties, so `"foo": "123"` becomes `"foo": 123` and ditto for `float` values. `wof:parent_id` I'm looking at you here.

Replacing empty string values which have `null` in the documents with an empty string, so `"foo": null` becomes `"foo": ""`

There'll be more of this as I make progress. But @thisisaaronland and/or @stepps00, please shout loudly if I'm going down a really wrong path here.

**Comment by vicchi** [comment]
Closing down this PR due to the comments above; a cut down version, which only fixes the case sensitive file naming clash is now in PR #65

**Pull request closed without merging**
